name: 'Build App'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-android-preview:
    uses: ./.github/workflows/build-app.yml
    secrets: inherit
    with:
      os: ubuntu-latest
      platform: android
      profile: preview

  build-ios-preview:
    uses: ./.github/workflows/build-app.yml
    secrets: inherit
    with:
      os: macos-latest
      platform: ios
      profile: preview

  build-android-development:
    uses: ./.github/workflows/build-app.yml
    secrets: inherit
    with:
      os: ubuntu-latest
      platform: android
      profile: development

  build-ios-development:
    uses: ./.github/workflows/build-app.yml
    secrets: inherit
    with:
      os: macos-latest
      platform: ios
      profile: development

  build:
    needs:
      [
        build-android-preview,
        build-ios-preview,
        build-android-development,
        build-ios-development,
      ]
    runs-on: ubuntu-latest

    steps:
      - name: 👷 Placeholder
        run: |
          echo "Hello World"
