name: 'Build App'

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-ios: &build
    runs-on: macos-latest
    env:
      SUIET_PLATFORM: ios
      SUIET_PROFILE: preview
    strategy:
      matrix:
        node: [16.x]
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: 🏗 Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          expo-version: latest
          eas-version: latest

      - name: 🏗 Setup EAS local builds
        run: yarn global add eas-cli-local-build-plugin

      - name: 📦 Install dependencies (root)
        run: |
          npm ci

      - name: 📦 Install dependencies
        working-directory: packages/expo
        run: |
          npm ci

      - name: 👷 Build app
        run: |
          cd packages/expo
          eas build --local \
            --non-interactive \
            --platform=$SUIET_PLATFORM \
            --profile=$SUIET_PROFILE
      - name: 📱 Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ env.SUIET_PLATFORM }}-${{ env.SUIET_PROFILE }}
          path: packages/expo/build-*

  build-android:
    <<: *build
    runs-on: ubuntu-latest
    env:
      SUIET_PLATFORM: android
      SUIET_PROFILE: preview

  build-all:
    depends-on: [build-ios, build-android]
    runs-on: ubuntu-latest

    steps:
      - name: 📱 Download iOS binary
        uses: actions/download-artifact@v2
        with:
          name: app-ios-preview
          path: packages/expo

      - name: 📱 Download Android binary
        uses: actions/download-artifact@v2
        with:
          name: app-android-preview
          path: packages/expo

      - name: 📱 Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: app-preview
          path: packages/expo/build-*
